web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'localhost'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost:30080'; gitlab_rails['gitlab_shell_ssh_port']=30022;
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '30080:30080'
    - '443:443'
    - '30022:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab_web_1'
    - '/srv/gitlab/logs:/var/log/gitlab_web_1'
    - '/srv/gitlab/data:/var/opt/gitlab_web_1'
